on:
  push:
    branches:
      - main

jobs:
   
  setup-i3gis-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        id: "setup-image-tag-i3gis"
        run: |
          echo "I3GIS_BINARY_PATH=Diary_with_lock_v4.90_apkpure.com.apk" >> $GITHUB_OUTPUT
    outputs:
      I3GIS_BINARY_PATH: ${{ steps.setup-image-tag-i3gis.outputs.I3GIS_BINARY_PATH }}
  
  i3gis-job:
    needs: setup-i3gis-env
    runs-on: ubuntu-latest
    outputs:
      I3GIS_APK_VERSION_ID: ${{ steps.scan-i3gis.outputs.I3GIS_APK_VERSION_ID }}
    steps:
      - name: Scan project android project 19 with i3gis
        id: "scan-i3gis"
        run: |
          curl -o Diary_with_lock_v4.90_apkpure.com.apk -LJO https://github.com/i3gis/SampleAPK/raw/95b00d2fab4a8d0110947cd066962a3314b6dc23/Diary%20with%20lock_v4.90_apkpure.com.apk
          echo "Scanning project android project 19 with i3gis..."
          scanResponse=$(curl --write-out '%{http_code}' --request POST -sL --url 'https://ontakaspi.my.id/mast/api/v1/integration/scan' --header 'Authorization: Bearer NKIXHVYgwWwe880HgM+v+00qn4wtgDMnNw/IuRmWuVFEjvCFxQtO7JanWUSst0OlvIInmkwCv2PVosaby8DRTtbksi6P1XUiRCk/Bcstb8ZczDFwTfn8eP6pvS52Ghxd1MwbGDAEPvXQXrDEjwNOtg==' -F 'apk_file=@"${{ needs.setup-i3gis-env.outputs.I3GIS_BINARY_PATH }}"' -F 'mobile_project_id=58')
          scanCode=$(echo $scanResponse | grep -o ...$)
          echo "HTTP response status code: $scanCode"
          if [ $scanCode = "200" ]; then
            echo "Scan project android project 19 with i3gis..."
          else
            echo "Response: $scanResponse"
            echo "Build failed because scan was not successful..."
            exit 1
          fi
          echo "Scan project android project 19 with i3gis is starting..."
          apkVersionId=$(echo "$scanResponse" | grep -o '"apk_version_id": *[0-9]*' | grep -o '[0-9]*')
          echo "I3GIS_APK_VERSION_ID=$apkVersionId" >> $GITHUB_OUTPUT

  i3gis-status-job:
    needs: i3gis-job
    runs-on: ubuntu-latest
    steps:
      - name: Get scan status
        run: |
          echo "Get scan status..."
          status_running=true
          while [ "$status_running" = true ]; do
            sleep 5
            echo "Scan still running..."
            checkResponse=$(curl --write-out ''%{http_code}'' --request GET -sL --url 'https://ontakaspi.my.id/mast/api/v1/integration/status/${{needs.i3gis-job.outputs.I3GIS_APK_VERSION_ID}}' --header 'Content-Type: application/json' --header 'Authorization: Bearer NKIXHVYgwWwe880HgM+v+00qn4wtgDMnNw/IuRmWuVFEjvCFxQtO7JanWUSst0OlvIInmkwCv2PVosaby8DRTtbksi6P1XUiRCk/Bcstb8ZczDFwTfn8eP6pvS52Ghxd1MwbGDAEPvXQXrDEjwNOtg==')
            checkCode=$(echo $checkResponse | grep -o ...$)
            echo "HTTP response status code: $checkCode"
            if [ $checkCode != "200" ] && [ $checkCode != "404" ]; then
              echo "Response: $checkResponse"
              echo "Scan failed..."
              exit 1
            fi
            if [ $checkCode = "404" ]; then
              echo "Scan finished..."
              status_running=false
            fi
          done
